# Generated by Django 5.2.9 on 2026-01-05 00:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Sinh viên'), ('instructor', 'Giảng viên'), ('admin', 'Quản trị viên')], default='student', max_length=20)),
                ('specialization', models.CharField(blank=True, help_text='Chuyên ngành (dành cho giảng viên)', max_length=100)),
                ('student_id', models.CharField(blank=True, help_text='Mã số sinh viên', max_length=20)),
                ('employee_id', models.CharField(blank=True, help_text='Mã số nhân viên', max_length=20)),
                ('academic_year', models.CharField(blank=True, help_text='Năm học (VD: 2024-2025)', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Số điện thoại', max_length=20)),
                ('profile_picture_url', models.URLField(blank=True, help_text='URL ảnh đại diện')),
                ('bio', models.TextField(blank=True, help_text='Tiểu sử cá nhân')),
                ('language_preference', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English')], default='vi', help_text='Ngôn ngữ ưa thích', max_length=10)),
                ('notification_settings', models.JSONField(default=dict, help_text='Cài đặt thông báo (email, in-app, etc.)')),
                ('email_verified', models.BooleanField(default=False, help_text='Email đã được xác minh')),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='Lần cuối thay đổi mật khẩu', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_token_id', models.CharField(default='legacy-token', help_text='Unique JWT token identifier', max_length=255, unique=True)),
                ('refresh_token_hash', models.CharField(default='', help_text='Hashed refresh token', max_length=255)),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('device_info', models.TextField(blank=True, help_text='Device and browser information')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the session', null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'accounts_session',
            },
        ),
    ]
