# Generated by Django 4.2.7 on 2025-10-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_department_alter_case_options_case_admission_date_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Khoa phòng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cases.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Số điện thoại', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, help_text='Chuyên ngành (dành cho giảng viên)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='Mã số sinh viên', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Sinh viên'), ('instructor', 'Giảng viên'), ('admin', 'Quản trị viên')], default='student', max_length=20),
        ),
    ]
