# Generated by Django 4.2.7 on 2025-10-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_department_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='device_info',
            field=models.TextField(blank=True, help_text='Device and browser information'),
        ),
        migrations.AddField(
            model_name='session',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the session', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='jwt_token_id',
            field=models.CharField(default='legacy-token', help_text='Unique JWT token identifier', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='session',
            name='refresh_token_hash',
            field=models.CharField(default='', help_text='Hashed refresh token', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Năm học (VD: 2024-2025)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Tiểu sử cá nhân'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email đã được xác minh'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Mã số nhân viên', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English')], default='vi', help_text='Ngôn ngữ ưa thích', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(default=dict, help_text='Cài đặt thông báo (email, in-app, etc.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='Lần cuối thay đổi mật khẩu', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='URL ảnh đại diện'),
        ),
    ]
