# Generated by Django 4.2.7 on 2025-10-03 03:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_scale', models.CharField(choices=[('percentage', 'Percentage (0-100)'), ('letter', 'Letter Grade (A-F)'), ('pass_fail', 'Pass/Fail'), ('points', 'Points')], default='percentage', max_length=20)),
                ('score', models.FloatField(help_text='Numeric score (0-100 for percentage, or custom range)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('letter_grade', models.CharField(blank=True, help_text='Letter grade (A, B, C, D, F, etc.)', max_length=5)),
                ('clinical_reasoning_score', models.FloatField(blank=True, help_text='Score for clinical reasoning (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('documentation_score', models.FloatField(blank=True, help_text='Score for documentation quality (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('presentation_score', models.FloatField(blank=True, help_text='Score for presentation (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('evaluation_notes', models.TextField(help_text='Detailed evaluation notes and comments')),
                ('strengths', models.TextField(blank=True, help_text="Student's strengths demonstrated in this case")),
                ('weaknesses', models.TextField(blank=True, help_text='Areas needing improvement')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for future learning')),
                ('is_final', models.BooleanField(default=True, help_text='Whether this is the final grade or a draft')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='cases.case')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades_grade',
                'ordering': ['-graded_at'],
            },
        ),
    ]
