# Generated by Django 4.2.7 on 2025-11-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_remove_grade_instructor_alter_grade_graded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grading_criteria',
            field=models.JSONField(blank=True, help_text='Detailed grading criteria: {history, examination, differential, treatment, presentation}', null=True),
        ),
    ]
