# Generated by Django 4.2.7 on 2025-10-03 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF Document'), ('word', 'Word Document'), ('powerpoint', 'PowerPoint Presentation'), ('json', 'JSON Data')], max_length=20)),
                ('file_path', models.FileField(help_text='Path to the exported file', upload_to='exports/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('template_used', models.CharField(blank=True, help_text='Export template used for generation', max_length=200)),
                ('export_settings', models.JSONField(default=dict, help_text='Settings used during export (e.g., include comments, anonymize)')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this export file should be deleted', null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Export',
                'verbose_name_plural': 'Case Exports',
                'db_table': 'exports_caseexport',
                'ordering': ['-exported_at'],
            },
        ),
    ]
