# Generated by Django 5.2.9 on 2026-01-05 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('vietnamese_name', models.CharField(help_text='Tên tiếng Việt', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('standard', 'Standard Medical Case'), ('academic', 'Academic/Teaching'), ('research', 'Research Publication'), ('clinical', 'Clinical Documentation'), ('presentation', 'Presentation Format'), ('anonymized', 'Anonymized/De-identified')], default='standard', max_length=50)),
                ('include_patient_details', models.BooleanField(default=True)),
                ('include_medical_history', models.BooleanField(default=True)),
                ('include_examination', models.BooleanField(default=True)),
                ('include_investigations', models.BooleanField(default=True)),
                ('include_diagnosis', models.BooleanField(default=True)),
                ('include_treatment', models.BooleanField(default=True)),
                ('include_learning_objectives', models.BooleanField(default=True)),
                ('include_comments', models.BooleanField(default=False)),
                ('include_attachments', models.BooleanField(default=True)),
                ('include_grades', models.BooleanField(default=False)),
                ('anonymize_patient', models.BooleanField(default=False)),
                ('add_watermark', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(blank=True, max_length=200)),
                ('header_text', models.TextField(blank=True, help_text='Custom header content')),
                ('footer_text', models.TextField(blank=True, help_text='Custom footer content')),
                ('logo_url', models.URLField(blank=True, help_text='Institution logo URL')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_template', models.BooleanField(default=False, help_text='System-provided template (cannot be deleted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_export_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Template',
                'verbose_name_plural': 'Export Templates',
                'db_table': 'exports_exporttemplate',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF Document'), ('word', 'Word Document'), ('powerpoint', 'PowerPoint Presentation'), ('json', 'JSON Data')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('file_path', models.FileField(blank=True, help_text='Path to the exported file', null=True, upload_to='exports/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash of the file', max_length=64)),
                ('export_settings', models.JSONField(default=dict, help_text='Settings used during export (e.g., include comments, anonymize)')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this export file should be deleted', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='cases.case')),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='exports.exporttemplate')),
            ],
            options={
                'verbose_name': 'Case Export',
                'verbose_name_plural': 'Case Exports',
                'db_table': 'exports_caseexport',
                'ordering': ['-exported_at'],
                'indexes': [models.Index(fields=['exported_by', '-exported_at'], name='exports_cas_exporte_a14949_idx'), models.Index(fields=['case', '-exported_at'], name='exports_cas_case_id_d2a309_idx'), models.Index(fields=['status', '-exported_at'], name='exports_cas_status_6a11d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatchExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF Document'), ('word', 'Word Document'), ('powerpoint', 'PowerPoint Presentation'), ('json', 'JSON Data')], max_length=20)),
                ('batch_name', models.CharField(blank=True, max_length=200)),
                ('export_settings', models.JSONField(default=dict)),
                ('compress_output', models.BooleanField(default=True, help_text='Compress exports into a ZIP file')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('processed_cases', models.PositiveIntegerField(default=0)),
                ('failed_cases', models.PositiveIntegerField(default=0)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='exports/batch/%Y/%m/%d/')),
                ('zip_file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('cases', models.ManyToManyField(related_name='batch_exports', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_exports', to=settings.AUTH_USER_MODEL)),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_exports', to='exports.exporttemplate')),
            ],
            options={
                'verbose_name': 'Batch Export',
                'verbose_name_plural': 'Batch Exports',
                'db_table': 'exports_batchexport',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='exports_bat_user_id_d90773_idx'), models.Index(fields=['status', '-created_at'], name='exports_bat_status_fafb78_idx')],
            },
        ),
    ]
