# Generated by Django 4.2.7 on 2025-11-14 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseexport',
            old_name='user',
            new_name='exported_by',
        ),
    ]
