# Generated by Django 4.2.7 on 2025-11-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_rename_user_caseexport_exported_by'),
    ]

    operations = [
        # Index doesn't exist anymore since we deleted the migration that created it
        # migrations.RemoveIndex(
        #     model_name='caseexport',
        #     name='exports_cas_user_id_5a08f1_idx',
        # ),
        migrations.AddIndex(
            model_name='caseexport',
            index=models.Index(fields=['exported_by', '-exported_at'], name='exports_cas_exporte_a14949_idx'),
        ),
    ]
