# Generated by Django 4.2.7 on 2025-10-03 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fields_schema', models.JSONField(help_text='JSON schema defining the template structure and required fields')),
                ('is_standard', models.BooleanField(default=False, help_text='Whether this is a standard template provided by the system')),
                ('specialty', models.CharField(help_text='Medical specialty this template is designed for', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Template',
                'verbose_name_plural': 'Case Templates',
                'db_table': 'templates_casetemplate',
                'ordering': ['specialty', 'name'],
            },
        ),
    ]
