# Generated by Django 4.2.7 on 2025-10-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_department_alter_case_options_case_admission_date_and_more'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casetemplate',
            options={'ordering': ['specialty', 'name'], 'verbose_name': 'Mẫu hồ sơ bệnh án', 'verbose_name_plural': 'Mẫu hồ sơ bệnh án'},
        ),
        migrations.AddField(
            model_name='casetemplate',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Khoa phòng sở hữu template này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='cases.department'),
        ),
        migrations.AlterField(
            model_name='casetemplate',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Template chuẩn do hệ thống cung cấp'),
        ),
        migrations.AlterField(
            model_name='casetemplate',
            name='specialty',
            field=models.CharField(help_text='Chuyên khoa mà template này được thiết kế', max_length=100),
        ),
    ]
