# Generated by Django 4.2.7 on 2025-10-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_alter_casetemplate_options_casetemplate_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetemplate',
            name='vietnamese_name',
            field=models.CharField(blank=True, help_text='Tên tiếng Việt', max_length=200),
        ),
    ]
