# Generated by Django 5.2.9 on 2026-01-05 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('comments', '0001_initial'),
        ('feedback', '0001_initial'),
        ('grades', '0001_initial'),
        ('inquiries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('grade', 'Grade'), ('comment', 'Comment'), ('submission', 'Submission'), ('assignment', 'Assignment'), ('reminder', 'Reminder'), ('feedback', 'Feedback'), ('case_review', 'Case Review'), ('permission_granted', 'Permission Granted'), ('inquiry', 'Inquiry'), ('system', 'System')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when clicking notification', max_length=500)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, help_text='Related case if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case')),
                ('related_comment', models.ForeignKey(blank=True, help_text='Related comment if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comments.comment')),
                ('related_feedback', models.ForeignKey(blank=True, help_text='Related feedback if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='feedback.feedback')),
                ('related_grade', models.ForeignKey(blank=True, help_text='Related grade if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='grades.grade')),
                ('related_inquiry', models.ForeignKey(blank=True, help_text='Related inquiry if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inquiries.inquiry')),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
