#!/bin/bash
set -e

echo "====================================================="
echo "Clinical Case Platform - PostgreSQL Test Setup"
echo "====================================================="
echo
echo "This script will set up a PostgreSQL test database"
echo "for the Clinical Case Platform development environment."
echo

# Check if PostgreSQL is installed
echo "Checking PostgreSQL installation..."
if ! command -v psql >/dev/null 2>&1; then
  echo "ERROR: PostgreSQL is not installed or not in PATH"
  echo "Please install PostgreSQL:"
  echo "  sudo apt install postgresql postgresql-client"
  exit 1
fi

echo "PostgreSQL found!"
echo

# Prompt for PostgreSQL admin credentials
read -p "PostgreSQL admin username (default: postgres): " PG_USER
PG_USER=${PG_USER:-postgres}

echo
echo "Connecting to PostgreSQL to create test database and user..."
echo "You may be prompted for the PostgreSQL admin password."
echo

# Create test database and user
psql -U "$PG_USER" -h localhost -p 5432 -c "DROP DATABASE IF EXISTS clinical_case_platform_test;" postgres
psql -U "$PG_USER" -h localhost -p 5432 -c "DROP ROLE IF EXISTS clinical_case_user;" postgres
psql -U "$PG_USER" -h localhost -p 5432 -c "CREATE DATABASE clinical_case_platform_test;" postgres
psql -U "$PG_USER" -h localhost -p 5432 -c "CREATE USER clinical_case_user WITH PASSWORD 'clinical_pass_2024';" postgres
psql -U "$PG_USER" -h localhost -p 5432 -c "GRANT ALL PRIVILEGES ON DATABASE clinical_case_platform_test TO clinical_case_user;" postgres
psql -U "$PG_USER" -h localhost -p 5432 -c "ALTER ROLE clinical_case_user CREATEDB;" postgres

echo
echo "====================================================="
echo "SUCCESS: Test database setup completed!"
echo "====================================================="
echo
echo "Database Details:"
echo "  Database Name: clinical_case_platform_test"
echo "  Username: clinical_case_user"
echo "  Password: clinical_pass_2024"
echo "  Host: localhost"
echo "  Port: 5432"
echo
echo "Creating/updating backend/.env.test file..."

cat <<EOF > backend/.env.test
# Test Environment Configuration
# Generated by setup_postgres_test.sh on $(date)
# Database Configuration
DB_NAME=clinical_case_platform_test
DB_USER=clinical_case_user
DB_PASSWORD=clinical_pass_2024
DB_HOST=localhost
DB_PORT=5432

# Django Configuration
SECRET_KEY=test-secret-key-change-in-production
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1

# CORS Configuration
CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173

# Media and Static Files
MEDIA_ROOT=media/
STATIC_ROOT=staticfiles/
EOF

echo
echo "Environment file created: backend/.env.test"
echo
echo "====================================================="
echo "Setup Complete! You can now run the Django backend."
echo "====================================================="
echo
echo "To start the backend with test settings:"
echo "  cd backend"
echo "  export DJANGO_SETTINGS_MODULE=clinical_case_platform.settings_test"
echo "  python manage.py runserver"
echo
echo "To start the frontend:"
echo "  cd frontend"
echo "  npm install"
echo "  npm run dev"
echo

