@echo off
echo =====================================================
echo Clinical Case Platform - PostgreSQL Test Setup
echo =====================================================
echo.
echo This script will set up a PostgreSQL test database
echo for the Clinical Case Platform development environment.
echo.

REM Check if PostgreSQL is installed and accessible
echo Checking PostgreSQL installation...
psql --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: PostgreSQL is not installed or not in PATH
    echo Please install PostgreSQL and ensure psql is accessible
    echo Download from: https://www.postgresql.org/download/windows/
    pause
    exit /b 1
)

echo PostgreSQL found!
echo.

REM Prompt for PostgreSQL admin credentials
echo Please enter your PostgreSQL admin credentials:
set /p PG_USER="PostgreSQL admin username (default: postgres): "
if "%PG_USER%"=="" set PG_USER=postgres

echo.
echo Connecting to PostgreSQL to create test database and user...
echo You will be prompted for the PostgreSQL admin password.
echo.

REM Create the test database and user
echo Creating test database and user...
psql -U %PG_USER% -h localhost -p 5432 -c "DROP DATABASE IF EXISTS clinical_case_platform_test;" postgres
psql -U %PG_USER% -h localhost -p 5432 -c "DROP USER IF EXISTS clinical_case_user;" postgres
psql -U %PG_USER% -h localhost -p 5432 -c "CREATE DATABASE clinical_case_platform_test;" postgres
psql -U %PG_USER% -h localhost -p 5432 -c "CREATE USER clinical_case_user WITH PASSWORD 'clinical_pass_2024';" postgres
psql -U %PG_USER% -h localhost -p 5432 -c "GRANT ALL PRIVILEGES ON DATABASE clinical_case_platform_test TO clinical_case_user;" postgres
psql -U %PG_USER% -h localhost -p 5432 -c "ALTER USER clinical_case_user CREATEDB;" postgres

if %errorlevel% neq 0 (
    echo.
    echo ERROR: Failed to create database or user
    echo Please check your PostgreSQL credentials and try again
    pause
    exit /b 1
)

echo.
echo =====================================================
echo SUCCESS: Test database setup completed!
echo =====================================================
echo.
echo Database Details:
echo - Database Name: clinical_case_platform_test
echo - Username: clinical_case_user
echo - Password: clinical_pass_2024
echo - Host: localhost
echo - Port: 5432
echo.
echo Next Steps:
echo 1. Update backend\.env.test with your database password
echo 2. Run: cd backend
echo 3. Run: pip install -r requirements.txt
echo 4. Run: python manage.py migrate --settings=clinical_case_platform.settings_test
echo 5. Run: python manage.py create_test_data --settings=clinical_case_platform.settings_test
echo.
echo Creating/updating .env.test file...

REM Create or update the .env.test file
(
echo # Test Environment Configuration
echo # Generated by setup_postgres_test.bat on %date% %time%
echo.
echo # Database Configuration
echo DB_NAME=clinical_case_platform_test
echo DB_USER=clinical_case_user
echo DB_PASSWORD=clinical_pass_2024
echo DB_HOST=localhost
echo DB_PORT=5432
echo.
echo # Django Configuration
echo SECRET_KEY=test-secret-key-change-in-production
echo DEBUG=True
echo ALLOWED_HOSTS=localhost,127.0.0.1
echo.
echo # CORS Configuration
echo CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
echo.
echo # Media and Static Files
echo MEDIA_ROOT=media/
echo STATIC_ROOT=staticfiles/
) > backend\.env.test

echo.
echo Environment file created: backend\.env.test
echo.
echo =====================================================
echo Setup Complete! You can now run the Django backend.
echo =====================================================
echo.
echo To start the backend with test settings:
echo   cd backend
echo   set DJANGO_SETTINGS_MODULE=clinical_case_platform.settings_test
echo   python manage.py runserver
echo.
echo To start the frontend:
echo   cd frontend
echo   npm install
echo   npm run dev
echo.
pause