# Generated by Django 4.2.7 on 2025-10-03 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repositories', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('patient_name', models.CharField(help_text='Patient name (can be anonymized)', max_length=200)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'Not Specified')], max_length=20)),
                ('medical_record_number', models.CharField(blank=True, help_text='Medical record number (anonymized)', max_length=50)),
                ('history', models.TextField(help_text='Patient history and presenting complaint')),
                ('examination', models.TextField(help_text='Physical examination findings')),
                ('diagnosis', models.TextField(help_text='Diagnosis and differential diagnosis')),
                ('treatment', models.TextField(help_text='Treatment plan and management')),
                ('investigations', models.TextField(blank=True, help_text='Laboratory results, imaging, and other investigations')),
                ('follow_up', models.TextField(blank=True, help_text='Follow-up plan and outcomes')),
                ('learning_objectives', models.TextField(blank=True, help_text='Key learning points from this case')),
                ('case_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('specialty', models.CharField(help_text='Medical specialty relevant to this case', max_length=100)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='repositories.repository')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='templates.casetemplate')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'cases_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CasePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View Only'), ('comment', 'View and Comment'), ('edit', 'View, Comment and Edit')], default='view', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='cases.case')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Permission',
                'verbose_name_plural': 'Case Permissions',
                'db_table': 'cases_casepermission',
                'unique_together': {('case', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['specialty'], name='cases_case_special_3e7be9_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_status'], name='cases_case_case_st_46849d_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='cases_case_created_a9dee7_idx'),
        ),
    ]
