# Generated by Django 4.2.7 on 2025-10-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('head_of_department', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cases_department',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hồ sơ bệnh án', 'verbose_name_plural': 'Hồ sơ bệnh án'},
        ),
        migrations.AddField(
            model_name='case',
            name='admission_date',
            field=models.DateField(blank=True, help_text='Ngày nhập viện', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='discharge_date',
            field=models.DateField(blank=True, help_text='Ngày xuất viện', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('submitted', 'Đã nộp'), ('reviewed', 'Đã xem xét'), ('approved', 'Đã phê duyệt')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Chẩn đoán (sử dụng diagnosis_management để chi tiết hơn)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='examination',
            field=models.TextField(blank=True, help_text='Khám lâm sàng (sử dụng physical_examination để chi tiết hơn)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='follow_up',
            field=models.TextField(blank=True, help_text='Theo dõi'),
        ),
        migrations.AlterField(
            model_name='case',
            name='history',
            field=models.TextField(blank=True, help_text='Tiền sử bệnh nhân (sử dụng clinical_history để chi tiết hơn)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='investigations',
            field=models.TextField(blank=True, help_text='Xét nghiệm (sử dụng investigations_detail để chi tiết hơn)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='keywords',
            field=models.CharField(blank=True, help_text='Từ khóa tìm kiếm, phân cách bằng dấu phẩy', max_length=500),
        ),
        migrations.AlterField(
            model_name='case',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='Mục tiêu học tập (sử dụng learning_outcomes để chi tiết hơn)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='medical_record_number',
            field=models.CharField(blank=True, help_text='Số hồ sơ bệnh án (ẩn danh)', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='patient_age',
            field=models.PositiveIntegerField(help_text='Tuổi'),
        ),
        migrations.AlterField(
            model_name='case',
            name='patient_gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác'), ('not_specified', 'Không xác định')], help_text='Giới tính', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='patient_name',
            field=models.CharField(help_text='Tên bệnh nhân (có thể ẩn danh)', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='specialty',
            field=models.CharField(help_text='Chuyên khoa liên quan đến ca bệnh này', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='treatment',
            field=models.TextField(blank=True, help_text='Điều trị (sử dụng diagnosis_management để chi tiết hơn)'),
        ),
        migrations.CreateModel(
            name='PhysicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_appearance', models.TextField(help_text='Thể trạng chung')),
                ('vital_signs', models.TextField(help_text='Dấu hiệu sinh tồn (nhiệt độ, mạch, huyết áp, nhịp thở)')),
                ('head_neck', models.TextField(blank=True, help_text='Đầu và cổ')),
                ('cardiovascular', models.TextField(blank=True, help_text='Tim mạch')),
                ('respiratory', models.TextField(blank=True, help_text='Hô hấp')),
                ('abdominal', models.TextField(blank=True, help_text='Bụng')),
                ('neurological', models.TextField(blank=True, help_text='Thần kinh')),
                ('musculoskeletal', models.TextField(blank=True, help_text='Cơ xương khớp')),
                ('skin', models.TextField(blank=True, help_text='Da')),
                ('other_systems', models.TextField(blank=True, help_text='Các hệ khác')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_examination', to='cases.case')),
            ],
            options={
                'verbose_name': 'Physical Examination',
                'verbose_name_plural': 'Physical Examinations',
                'db_table': 'cases_physicalexamination',
            },
        ),
        migrations.CreateModel(
            name='LearningOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_objectives', models.TextField(help_text='Mục tiêu học tập')),
                ('key_concepts', models.TextField(blank=True, help_text='Khái niệm chính')),
                ('clinical_pearls', models.TextField(blank=True, help_text='Kinh nghiệm lâm sàng')),
                ('references', models.TextField(blank=True, help_text='Tài liệu tham khảo')),
                ('discussion_points', models.TextField(blank=True, help_text='Điểm thảo luận')),
                ('assessment_criteria', models.TextField(blank=True, help_text='Tiêu chí đánh giá')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='cases.case')),
            ],
            options={
                'verbose_name': 'Learning Outcome',
                'verbose_name_plural': 'Learning Outcomes',
                'db_table': 'cases_learningoutcomes',
            },
        ),
        migrations.CreateModel(
            name='Investigations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_results', models.TextField(blank=True, help_text='Kết quả xét nghiệm tổng quát')),
                ('imaging_studies', models.TextField(blank=True, help_text='Chẩn đoán hình ảnh (X-quang, CT, MRI, siêu âm)')),
                ('ecg_findings', models.TextField(blank=True, help_text='Điện tim')),
                ('pathology_results', models.TextField(blank=True, help_text='Kết quả giải phẫu bệnh')),
                ('special_tests', models.TextField(blank=True, help_text='Các xét nghiệm đặc biệt')),
                ('microbiology', models.TextField(blank=True, help_text='Vi sinh')),
                ('biochemistry', models.TextField(blank=True, help_text='Sinh hóa')),
                ('hematology', models.TextField(blank=True, help_text='Huyết học')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigations_detail', to='cases.case')),
            ],
            options={
                'verbose_name': 'Investigation',
                'verbose_name_plural': 'Investigations',
                'db_table': 'cases_investigations',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_diagnosis', models.TextField(help_text='Chẩn đoán chính')),
                ('differential_diagnosis', models.TextField(blank=True, help_text='Chẩn đoán phân biệt')),
                ('icd10_codes', models.CharField(blank=True, help_text='Mã ICD-10', max_length=200)),
                ('treatment_plan', models.TextField(help_text='Kế hoạch điều trị')),
                ('medications_prescribed', models.TextField(blank=True, help_text='Thuốc được kê đơn')),
                ('procedures_performed', models.TextField(blank=True, help_text='Các thủ thuật đã thực hiện')),
                ('follow_up_plan', models.TextField(blank=True, help_text='Kế hoạch theo dõi')),
                ('prognosis', models.TextField(blank=True, help_text='Tiên lượng')),
                ('complications', models.TextField(blank=True, help_text='Biến chứng')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_management', to='cases.case')),
            ],
            options={
                'verbose_name': 'Diagnosis & Management',
                'verbose_name_plural': 'Diagnosis & Management',
                'db_table': 'cases_diagnosismanagement',
            },
        ),
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(help_text='Lý do chính đến khám')),
                ('history_present_illness', models.TextField(help_text='Tiền sử bệnh hiện tại')),
                ('past_medical_history', models.TextField(blank=True, help_text='Tiền sử bệnh tật')),
                ('family_history', models.TextField(blank=True, help_text='Tiền sử gia đình')),
                ('social_history', models.TextField(blank=True, help_text='Tiền sử xã hội (hút thuốc, uống rượu, v.v.)')),
                ('allergies', models.TextField(blank=True, help_text='Dị ứng')),
                ('medications', models.TextField(blank=True, help_text='Thuốc đang sử dụng')),
                ('review_systems', models.TextField(blank=True, help_text='Hỏi bệnh theo hệ thống')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_history', to='cases.case')),
            ],
            options={
                'verbose_name': 'Clinical History',
                'verbose_name_plural': 'Clinical Histories',
                'db_table': 'cases_clinicalhistory',
            },
        ),
    ]
