# Generated by Django 5.2.7 on 2025-12-01 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("repositories", "0001_initial"),
        ("templates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="repositories.repository",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người xem xét ca bệnh",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="templates.casetemplate",
            ),
        ),
        migrations.AddField(
            model_name="caseanalytics",
            name="case",
            field=models.OneToOneField(
                help_text="Ca bệnh được theo dõi",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="casegroup",
            name="cases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ca bệnh trong nhóm",
                related_name="case_groups",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="casegroup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_case_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casepermission",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="casepermission",
            name="granted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="granted_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casepermission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casequalitymetrics",
            name="case",
            field=models.OneToOneField(
                help_text="Ca bệnh",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_metrics",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="casesubmissionworkflow",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người phê duyệt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casesubmissionworkflow",
            name="assigned_reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="Người xem xét được chỉ định",
                limit_choices_to={"role__in": ["instructor", "admin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_case_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casesubmissionworkflow",
            name="case",
            field=models.OneToOneField(
                help_text="Ca bệnh",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_workflow",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="casesubmissionworkflow",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người nộp",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casevalidationresult",
            name="case",
            field=models.ForeignKey(
                help_text="Ca bệnh được kiểm tra",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_results",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="casevalidationresult",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người thực hiện kiểm tra (null = tự động)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_validations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casevalidationrule",
            name="applies_to_templates",
            field=models.ManyToManyField(
                blank=True,
                help_text="Áp dụng cho các template cụ thể (để trống = tất cả)",
                related_name="validation_rules",
                to="templates.casetemplate",
            ),
        ),
        migrations.AddField(
            model_name="casevalidationrule",
            name="created_by",
            field=models.ForeignKey(
                help_text="Người tạo quy tắc",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_validation_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="caseviewlog",
            name="case",
            field=models.ForeignKey(
                help_text="Ca bệnh được xem",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_logs",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="caseviewlog",
            name="user",
            field=models.ForeignKey(
                help_text="Người xem",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinicalhistory",
            name="case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinical_history",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="clinicalhistory",
            name="documented_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người ghi chép tiền sử",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documented_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casepermission",
            name="target_department",
            field=models.ForeignKey(
                blank=True,
                help_text="Khoa được chia sẻ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_cases",
                to="cases.department",
            ),
        ),
        migrations.AddField(
            model_name="casegroup",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_groups",
                to="cases.department",
            ),
        ),
        migrations.AddField(
            model_name="departmentanalytics",
            name="department",
            field=models.ForeignKey(
                help_text="Khoa phòng",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="cases.department",
            ),
        ),
        migrations.AddField(
            model_name="diagnosismanagement",
            name="case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnosis_management",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="diagnosismanagement",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người quản lý điều trị",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_diagnoses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guestaccess",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_accesses",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="guestaccess",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_guest_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investigations_detail",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="ordered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người chỉ định xét nghiệm",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordered_investigations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="investigations",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người xem xét kết quả",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_investigations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="learningoutcomes",
            name="case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_outcomes",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="medicalattachment",
            name="allowed_instructors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "instructor"},
                related_name="restricted_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicalattachment",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_attachments",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="medicalattachment",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Khoa thực hiện",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cases.department",
            ),
        ),
        migrations.AddField(
            model_name="medicalattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="Người tải lên",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="medicalterm",
            index=models.Index(fields=["term"], name="cases_medic_term_a7f837_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalterm",
            index=models.Index(
                fields=["vietnamese_term"], name="cases_medic_vietnam_801c39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalterminologycheck",
            index=models.Index(fields=["term"], name="cases_medic_term_218c7f_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalterminologycheck",
            index=models.Index(
                fields=["category"], name="cases_medic_categor_7fc1cf_idx"
            ),
        ),
        migrations.AddField(
            model_name="permissionauditlog",
            name="actor_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Người thực hiện hành động",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="permissionauditlog",
            name="case",
            field=models.ForeignKey(
                help_text="Ca bệnh liên quan",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_audit_logs",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="permissionauditlog",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Người dùng được ảnh hưởng",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permission_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="physicalexamination",
            name="case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="physical_examination",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="physicalexamination",
            name="examined_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người thực hiện khám",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conducted_examinations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="platformusagestatistics",
            index=models.Index(
                fields=["period_type", "period_start"],
                name="cases_platf_period__4faf81_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="platformusagestatistics",
            unique_together={("period_type", "period_start")},
        ),
        migrations.AddField(
            model_name="studentengagementmetrics",
            name="student",
            field=models.OneToOneField(
                help_text="Sinh viên",
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engagement_metrics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentnotes",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_notes",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="studentnotes",
            name="student",
            field=models.ForeignKey(
                help_text="Student who created these notes",
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_case_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["specialty"], name="cases_case_special_3e7be9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["case_status"], name="cases_case_case_st_46849d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["created_at"], name="cases_case_created_a9dee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casesubmissionworkflow",
            index=models.Index(
                fields=["current_status"], name="cases_cases_current_c2e1dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casesubmissionworkflow",
            index=models.Index(
                fields=["assigned_reviewer"], name="cases_cases_assigne_4e0582_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casesubmissionworkflow",
            index=models.Index(
                fields=["submitted_at"], name="cases_cases_submitt_00356d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casevalidationresult",
            index=models.Index(
                fields=["case", "validation_status"],
                name="cases_casev_case_id_1e23f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="casevalidationresult",
            index=models.Index(
                fields=["validated_at"], name="cases_casev_validat_569448_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseviewlog",
            index=models.Index(
                fields=["case", "user"], name="cases_casev_case_id_117e71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseviewlog",
            index=models.Index(
                fields=["viewed_at"], name="cases_casev_viewed__d150d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseviewlog",
            index=models.Index(
                fields=["user", "viewed_at"], name="cases_casev_user_id_7aca61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casepermission",
            index=models.Index(
                fields=["case", "user"], name="cases_casep_case_id_bfb571_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casepermission",
            index=models.Index(
                fields=["case", "share_type"], name="cases_casep_case_id_c7e468_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casepermission",
            index=models.Index(
                fields=["target_department"], name="cases_casep_target__999dc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casepermission",
            index=models.Index(
                fields=["expires_at"], name="cases_casep_expires_588057_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casegroup",
            index=models.Index(
                fields=["department", "group_type"],
                name="cases_caseg_departm_6f64c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="casegroup",
            index=models.Index(
                fields=["class_identifier"], name="cases_caseg_class_i_50e8a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casegroup",
            index=models.Index(
                fields=["created_by"], name="cases_caseg_created_cadd60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentanalytics",
            index=models.Index(
                fields=["department", "period_start"],
                name="cases_depar_departm_5fcd08_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="departmentanalytics",
            unique_together={("department", "period_start")},
        ),
        migrations.AddIndex(
            model_name="guestaccess",
            index=models.Index(
                fields=["access_token"], name="cases_guest_access__e5ff09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestaccess",
            index=models.Index(fields=["case"], name="cases_guest_case_id_87f2e2_idx"),
        ),
        migrations.AddIndex(
            model_name="guestaccess",
            index=models.Index(
                fields=["expires_at"], name="cases_guest_expires_5e393f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalattachment",
            index=models.Index(
                fields=["case", "attachment_type"],
                name="cases_medic_case_id_dd5bb6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalattachment",
            index=models.Index(
                fields=["uploaded_at"], name="cases_medic_uploade_c29c7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalattachment",
            index=models.Index(
                fields=["attachment_type"], name="cases_medic_attachm_92d83c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["case", "action"], name="cases_permi_case_id_d1336f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["target_user"], name="cases_permi_target__9e532d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["actor_user"], name="cases_permi_actor_u_3b48cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["created_at"], name="cases_permi_created_e94b46_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentnotes",
            unique_together={("case", "student")},
        ),
    ]
