# Generated by Django 4.2.7 on 2025-10-12 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_department_alter_case_options_case_admission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Tệp đính kèm y tế', upload_to='medical_attachments/%Y/%m/%d/')),
                ('attachment_type', models.CharField(choices=[('xray', 'Ảnh chụp X-quang'), ('ct_scan', 'Ảnh chụp CT'), ('mri', 'Ảnh chụp MRI'), ('ultrasound', 'Ảnh siêu âm'), ('ecg', 'Điện tim đồ'), ('lab_report', 'Phiếu xét nghiệm'), ('blood_test', 'Kết quả xét nghiệm máu'), ('urine_test', 'Kết quả xét nghiệm nước tiểu'), ('pathology', 'Kết quả giải phẫu bệnh'), ('injury_photo', 'Ảnh chụp chấn thương'), ('surgical_photo', 'Ảnh phẫu thuật'), ('endoscopy', 'Ảnh nội soi'), ('prescription', 'Đơn thuốc'), ('discharge_summary', 'Tóm tắt xuất viện'), ('consent_form', 'Phiếu đồng ý'), ('other', 'Khác')], help_text='Loại tệp đính kèm', max_length=20)),
                ('title', models.CharField(help_text='Tiêu đề mô tả tệp', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về tệp')),
                ('date_taken', models.DateTimeField(blank=True, help_text='Ngày chụp/thực hiện', null=True)),
                ('physician_notes', models.TextField(blank=True, help_text='Ghi chú của bác sĩ')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Kích thước tệp (bytes)', null=True)),
                ('file_type', models.CharField(blank=True, help_text='Loại tệp (MIME type)', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_confidential', models.BooleanField(default=False, help_text='Tệp bảo mật (chỉ bác sĩ xem được)')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_attachments', to='cases.case')),
                ('department', models.ForeignKey(blank=True, help_text='Khoa thực hiện', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.department')),
                ('uploaded_by', models.ForeignKey(help_text='Người tải lên', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Attachment',
                'verbose_name_plural': 'Medical Attachments',
                'db_table': 'cases_medicalattachment',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['case', 'attachment_type'], name='cases_medic_case_id_dd5bb6_idx'), models.Index(fields=['uploaded_at'], name='cases_medic_uploade_c29c7f_idx'), models.Index(fields=['attachment_type'], name='cases_medic_attachm_92d83c_idx')],
            },
        ),
    ]
