# Generated by Django 5.2.7 on 2025-12-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalattachment",
            name="is_confidential",
            field=models.BooleanField(
                default=False, help_text="Đánh dấu tệp là bảo mật"
            ),
        ),
    ]
