# Generated by Django 5.2.8 on 2026-01-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cloned_from_instructor_name',
            field=models.CharField(blank=True, help_text='Tên giảng viên gốc nếu ca này được sao chép từ một ca khác của giảng viên', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='cloned_from_title',
            field=models.CharField(blank=True, help_text='Tiêu đề ca gốc nếu ca này được sao chép từ một ca khác của giảng viên', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='clones',
            field=models.ManyToManyField(blank=True, help_text='Các ca được sao chép từ ca này', related_name='original_case', to='cases.case'),
        ),
    ]
