# Generated by Django 5.2.7 on 2026-01-18 10:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_cloned_from_instructor_name_and_more'),
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, help_text='Precomputed full-text search vector', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='search_text',
            field=models.TextField(blank=True, editable=False, help_text='Normalized text for trigram similarity search', null=True),
        ),
        migrations.AddIndex(
            model_name='case',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='cases_case_search_document_gin'),
        ),
        migrations.RunSQL(
            sql=[
                # Enable required extensions
                "CREATE EXTENSION IF NOT EXISTS unaccent;",
                "CREATE EXTENSION IF NOT EXISTS pg_trgm;",

                # Trigram index for fuzzy search
                """
                CREATE INDEX IF NOT EXISTS cases_case_search_text_trgm
                ON cases_case
                USING GIN (search_text gin_trgm_ops);
                """
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS cases_case_search_text_trgm;"
            ],
        ),
    ]
