# Generated by Django 4.2.7 on 2025-10-27 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0003_medicalattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='Người lưu trữ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='average_rating',
            field=models.FloatField(blank=True, help_text='Đánh giá trung bình', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_summary',
            field=models.TextField(blank=True, help_text='Tóm tắt ca bệnh'),
        ),
        migrations.AddField(
            model_name='case',
            name='chief_complaint_brief',
            field=models.CharField(blank=True, help_text='Lý do khám ngắn gọn', max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='complexity_level',
            field=models.CharField(choices=[('basic', 'Cơ bản'), ('intermediate', 'Trung cấp'), ('advanced', 'Nâng cao'), ('expert', 'Chuyên gia')], default='basic', help_text='Mức độ phức tạp', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='estimated_study_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Số giờ học ước tính', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Ngày theo dõi', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Đã lưu trữ'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Ca bệnh công khai'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_template_based',
            field=models.BooleanField(default=False, help_text='Dựa trên template'),
        ),
        migrations.AddField(
            model_name='case',
            name='learning_tags',
            field=models.CharField(blank=True, help_text='Tags học tập, phân cách bằng dấu phẩy', max_length=500),
        ),
        migrations.AddField(
            model_name='case',
            name='patient_ethnicity',
            field=models.CharField(blank=True, help_text='Dân tộc bệnh nhân', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='patient_occupation',
            field=models.CharField(blank=True, help_text='Nghề nghiệp bệnh nhân', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='priority_level',
            field=models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', help_text='Mức độ ưu tiên', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='requires_follow_up',
            field=models.BooleanField(default=False, help_text='Yêu cầu theo dõi'),
        ),
        migrations.AddField(
            model_name='case',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Người xem xét', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Số lượt xem'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='documented_by',
            field=models.ForeignKey(blank=True, help_text='Người ghi chép', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documented_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='symptom_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Số ngày có triệu chứng', null=True),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='symptom_onset',
            field=models.CharField(blank=True, help_text='Khởi phát triệu chứng (acute/chronic/subacute)', max_length=50),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='symptom_progression',
            field=models.CharField(blank=True, help_text='Tiến triển triệu chứng', max_length=100),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email liên hệ', max_length=254),
        ),
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('clinical', 'Lâm sàng'), ('paraclinical', 'Cận lâm sàng'), ('administrative', 'Hành chính')], default='clinical', help_text='Loại khoa phòng', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='vietnamese_name',
            field=models.CharField(blank=True, help_text='Tên tiếng Việt', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosismanagement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosismanagement',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='Người quản lý điều trị', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosismanagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='investigations',
            name='arterial_blood_gas',
            field=models.TextField(blank=True, help_text='Khí máu động mạch'),
        ),
        migrations.AddField(
            model_name='investigations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigations',
            name='creatinine_level',
            field=models.FloatField(blank=True, help_text='Creatinine (mg/dL)', null=True),
        ),
        migrations.AddField(
            model_name='investigations',
            name='ecg_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Tần số tim trên ECG (bpm)', null=True),
        ),
        migrations.AddField(
            model_name='investigations',
            name='ecg_rhythm',
            field=models.CharField(blank=True, help_text='Nhịp tim trên ECG', max_length=50),
        ),
        migrations.AddField(
            model_name='investigations',
            name='glucose_level',
            field=models.FloatField(blank=True, help_text='Glucose (mg/dL)', null=True),
        ),
        migrations.AddField(
            model_name='investigations',
            name='hemoglobin_level',
            field=models.FloatField(blank=True, help_text='Hemoglobin (g/dL)', null=True),
        ),
        migrations.AddField(
            model_name='investigations',
            name='ordered_by',
            field=models.ForeignKey(blank=True, help_text='Người chỉ định', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_investigations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigations',
            name='ph_level',
            field=models.FloatField(blank=True, help_text='Độ pH máu', null=True),
        ),
        migrations.AddField(
            model_name='investigations',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Người xem xét kết quả', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_investigations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='investigations',
            name='white_cell_count',
            field=models.PositiveIntegerField(blank=True, help_text='Số lượng bạch cầu (/μL)', null=True),
        ),
        migrations.AddField(
            model_name='learningoutcomes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningoutcomes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='bmi',
            field=models.FloatField(blank=True, help_text='Chỉ số BMI', null=True),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='consciousness_level',
            field=models.CharField(blank=True, help_text='Mức độ ý thức', max_length=50),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='examined_by',
            field=models.ForeignKey(blank=True, help_text='Người thăm khám', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_examinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='height_cm',
            field=models.FloatField(blank=True, help_text='Chiều cao (cm)', null=True),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='vital_signs_bp',
            field=models.CharField(blank=True, help_text='Huyết áp (mmHg)', max_length=20),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='vital_signs_hr',
            field=models.PositiveIntegerField(blank=True, help_text='Nhịp tim (bpm)', null=True),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='vital_signs_rr',
            field=models.PositiveIntegerField(blank=True, help_text='Nhịp thở (bpm)', null=True),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='vital_signs_spo2',
            field=models.PositiveIntegerField(blank=True, help_text='SpO2 (%)', null=True),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='vital_signs_temp',
            field=models.FloatField(blank=True, help_text='Nhiệt độ (°C)', null=True),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='Cân nặng (kg)', null=True),
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='vital_signs',
            field=models.TextField(help_text='Dấu hiệu sinh tồn tổng hợp'),
        ),
    ]
