# Generated by Django 4.2.7 on 2025-11-01 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0004_case_archived_at_case_archived_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='Người lưu trữ ca bệnh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Người xem xét ca bệnh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_assessment', models.TextField(blank=True, help_text="Student's initial clinical assessment and key findings")),
                ('differential_diagnosis', models.TextField(blank=True, help_text="Student's differential diagnosis list with reasoning")),
                ('treatment_plan', models.TextField(blank=True, help_text="Student's proposed treatment plan and management strategy")),
                ('learning_reflections', models.TextField(blank=True, help_text='What the student learned from this case')),
                ('questions_for_instructor', models.TextField(blank=True, help_text='Questions or areas where the student needs clarification')),
                ('challenges_faced', models.TextField(blank=True, help_text='Challenges or difficulties encountered during the case')),
                ('resources_used', models.TextField(blank=True, help_text='References, textbooks, or resources consulted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_submitted', models.BooleanField(default=False, help_text='Whether these notes have been submitted for instructor review')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the notes were submitted', null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='cases.case')),
                ('student', models.ForeignKey(help_text='Student who created these notes', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='my_case_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Notes',
                'verbose_name_plural': 'Student Notes',
                'db_table': 'cases_studentnotes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
