# Generated by Django 5.2.7 on 2026-01-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_search_document_case_search_text_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Drop existing dictionary (safe re-run)
                "DROP TEXT SEARCH DICTIONARY IF EXISTS public.vietnamese;",

                # Create a portable dictionary that does not depend on
                # postgres server filesystem stopword files.
                """
                CREATE TEXT SEARCH DICTIONARY public.vietnamese (
                    TEMPLATE = pg_catalog.simple
                );
                """,

                # Create configuration copied from english
                """
                CREATE TEXT SEARCH CONFIGURATION public.vietnamese (
                    COPY = pg_catalog.english
                );
                """,

                # Map word types to vietnamese dictionary
                """
                ALTER TEXT SEARCH CONFIGURATION public.vietnamese
                    ALTER MAPPING
                        FOR asciiword, asciihword, hword_asciipart,
                            hword, hword_part, word
                        WITH vietnamese;
                """
            ],
            reverse_sql=[
                "DROP TEXT SEARCH CONFIGURATION IF EXISTS public.vietnamese;",
                "DROP TEXT SEARCH DICTIONARY IF EXISTS public.vietnamese;",
            ],
        ),
    ]
