# Generated by Django 5.2.7 on 2026-02-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_add_vietnamese_fts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSearchToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('frequency', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='idx_token_prefix')],
            },
        ),
        #  Prefix optimization
        migrations.RunSQL(
            sql="""
                CREATE INDEX idx_token_prefix_pattern
                ON cases_casesearchtoken (token text_pattern_ops);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_token_prefix_pattern;
            """
        ),


    ]
