# Generated by Django 5.2.7 on 2025-11-05 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_alter_case_archived_by_alter_case_reviewed_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalhistory",
            name="documented_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người ghi chép tiền sử",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documented_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clinicalhistory",
            name="symptom_duration_days",
            field=models.PositiveIntegerField(
                blank=True, help_text="Thời gian có triệu chứng (ngày)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="clinicalhistory",
            name="symptom_onset",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sudden", "Đột ngột"),
                    ("gradual", "Từ từ"),
                    ("chronic", "Mạn tính"),
                ],
                help_text="Khởi phát triệu chứng",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="clinicalhistory",
            name="symptom_progression",
            field=models.CharField(
                blank=True,
                choices=[
                    ("improving", "Cải thiện"),
                    ("worsening", "Xấu đi"),
                    ("stable", "Ổn định"),
                    ("fluctuating", "Biến đổi"),
                ],
                help_text="Diễn biến triệu chứng",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="ecg_rate",
            field=models.PositiveIntegerField(
                blank=True, help_text="Tần số điện tim (bpm)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="ecg_rhythm",
            field=models.CharField(
                blank=True, help_text="Nhịp điện tim (sinus, AF, etc.)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="ordered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người chỉ định xét nghiệm",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordered_investigations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="ph_level",
            field=models.FloatField(blank=True, help_text="pH máu", null=True),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="white_cell_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Bạch cầu (cells/μL)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="physicalexamination",
            name="consciousness_level",
            field=models.CharField(
                choices=[
                    ("alert", "Tỉnh táo"),
                    ("drowsy", "Lơ mơ"),
                    ("stupor", "Hôn mê nông"),
                    ("coma", "Hôn mê sâu"),
                ],
                default="alert",
                help_text="Mức độ ý thức",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="physicalexamination",
            name="examined_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Người thực hiện khám",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conducted_examinations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="physicalexamination",
            name="vital_signs_hr",
            field=models.PositiveIntegerField(
                blank=True, help_text="Nhịp tim (lần/phút)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="physicalexamination",
            name="vital_signs_rr",
            field=models.PositiveIntegerField(
                blank=True, help_text="Nhịp thở (lần/phút)", null=True
            ),
        ),
    ]