# Generated by Django 5.2.7 on 2026-03-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_casesearchtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesearchtoken',
            name='display',
            field=models.CharField(default='', max_length=255),
        ),
    ]
