# Generated by Django 5.2.7 on 2025-11-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_clinicalhistory_documented_by_and_more'),
        ('cases', '0006_enhanced_case_sharing_permissions'),
    ]

    operations = [
    ]
