# Generated by Django 5.2.9 on 2026-03-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_casesearchtoken_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesearchtoken',
            name='display',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
