# Generated by Django 5.2.7 on 2025-11-11 01:44

import cases.medical_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_merge_20251110_1644'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='casegroup',
            new_name='cases_caseg_departm_6f64c9_idx',
            old_name='cases_casegroup_dept_type_idx',
        ),
        migrations.RenameIndex(
            model_name='casegroup',
            new_name='cases_caseg_class_i_50e8a3_idx',
            old_name='cases_casegroup_class_idx',
        ),
        migrations.RenameIndex(
            model_name='casegroup',
            new_name='cases_caseg_created_cadd60_idx',
            old_name='cases_casegroup_creator_idx',
        ),
        migrations.RenameIndex(
            model_name='casepermission',
            new_name='cases_casep_case_id_bfb571_idx',
            old_name='cases_caseperm_case_user_idx',
        ),
        migrations.RenameIndex(
            model_name='casepermission',
            new_name='cases_casep_case_id_c7e468_idx',
            old_name='cases_caseperm_case_share_idx',
        ),
        migrations.RenameIndex(
            model_name='casepermission',
            new_name='cases_casep_target__999dc2_idx',
            old_name='cases_caseperm_dept_idx',
        ),
        migrations.RenameIndex(
            model_name='casepermission',
            new_name='cases_casep_expires_588057_idx',
            old_name='cases_caseperm_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='guestaccess',
            new_name='cases_guest_access__e5ff09_idx',
            old_name='cases_guestaccess_token_idx',
        ),
        migrations.RenameIndex(
            model_name='guestaccess',
            new_name='cases_guest_case_id_87f2e2_idx',
            old_name='cases_guestaccess_case_idx',
        ),
        migrations.RenameIndex(
            model_name='guestaccess',
            new_name='cases_guest_expires_5e393f_idx',
            old_name='cases_guestaccess_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionauditlog',
            new_name='cases_permi_case_id_d1336f_idx',
            old_name='cases_auditlog_case_action_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionauditlog',
            new_name='cases_permi_target__9e532d_idx',
            old_name='cases_auditlog_target_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionauditlog',
            new_name='cases_permi_actor_u_3b48cf_idx',
            old_name='cases_auditlog_actor_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionauditlog',
            new_name='cases_permi_created_e94b46_idx',
            old_name='cases_auditlog_created_idx',
        ),
        migrations.AlterField(
            model_name='medicalattachment',
            name='attachment_type',
            field=models.CharField(choices=[('xray', 'Ảnh chụp X-quang'), ('ct_scan', 'Ảnh chụp CT'), ('mri', 'Ảnh chụp MRI'), ('ultrasound', 'Ảnh siêu âm'), ('ecg', 'Điện tim đồ'), ('lab_report', 'Phiếu xét nghiệm'), ('blood_test', 'Kết quả xét nghiệm máu'), ('urine_test', 'Kết quả xét nghiệm nước tiểu'), ('pathology', 'Kết quả giải phẫu bệnh'), ('injury_photo', 'Ảnh chụp chấn thương'), ('surgical_photo', 'Ảnh phẫu thuật'), ('endoscopy', 'Ảnh nội soi'), ('prescription', 'Đơn thuốc'), ('discharge_summary', 'Tóm tắt xuất viện'), ('consent_form', 'Phiếu đồng ý'), ('other', 'Khác')], help_text='Loại tệp đính kèm', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalattachment',
            name='file',
            field=models.FileField(help_text='Tệp đính kèm y tế', upload_to=cases.medical_models.medical_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='medicalattachment',
            name='file_type',
            field=models.CharField(blank=True, help_text='Loại tệp (MIME type)', max_length=200),
        ),
    ]
