# Generated by Django 4.2.7 on 2025-11-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_studentengagementmetrics_platformusagestatistics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='case',
            name='examination',
        ),
        migrations.RemoveField(
            model_name='case',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='case',
            name='history',
        ),
        migrations.RemoveField(
            model_name='case',
            name='investigations',
        ),
        migrations.RemoveField(
            model_name='case',
            name='learning_objectives',
        ),
        migrations.RemoveField(
            model_name='case',
            name='treatment',
        ),
    ]
