# Generated by Django 4.2.7 on 2025-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_remove_case_diagnosis_remove_case_examination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_vi', models.TextField(blank=True)),
                ('chapter', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cases_icd10code',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAbbreviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=64, unique=True)),
                ('expansion', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cases_medicalabbreviation',
            },
        ),
        migrations.CreateModel(
            name='MedicalTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Canonical term (prefer Vietnamese)', max_length=255)),
                ('vietnamese_term', models.CharField(blank=True, max_length=255)),
                ('english_term', models.CharField(blank=True, max_length=255)),
                ('synonyms', models.JSONField(blank=True, default=list, help_text='List of alternative terms/synonyms')),
                ('definition', models.TextField(blank=True)),
                ('specialty', models.CharField(blank=True, help_text='Medical specialty tag', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cases_medicalterm',
                'indexes': [models.Index(fields=['term'], name='cases_medic_term_a7f837_idx'), models.Index(fields=['vietnamese_term'], name='cases_medic_vietnam_801c39_idx')],
            },
        ),
    ]
