# Generated by Django 5.2.7 on 2025-11-15 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_icd10code_medicalabbreviation_medicalterm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalattachment',
            name='is_confidential',
        ),
        migrations.AddField(
            model_name='medicalattachment',
            name='allowed_instructors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'instructor'}, related_name='restricted_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalattachment',
            name='confidentiality_level',
            field=models.CharField(choices=[('public', 'Public (all collaborators)'), ('confidential', 'Confidential (instructors + owner)'), ('restricted', 'Restricted (owner + designated instructors)'), ('department', 'Department only')], default='public', help_text='Mức độ bảo mật của tệp', max_length=50),
        ),
    ]
