# Generated by Django 4.2.7 on 2025-11-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_social_media_feed'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='case',
            name='cases_case_pub_feed_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_case_feed_vis_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_case_featured_idx',
        ),
    ]
