# Generated by Django 4.2.7 on 2025-11-29 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0015_remove_case_cases_case_pub_feed_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnotes',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='cases.case'),
        ),
        migrations.AlterUniqueTogether(
            name='studentnotes',
            unique_together={('case', 'student')},
        ),
    ]
