# Generated by Django 5.2.9 on 2026-01-05 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('is_instructor_feedback', models.BooleanField(default=False, help_text='Whether this comment is official instructor feedback')),
                ('is_reaction', models.BooleanField(default=False, help_text='True if this is a reaction/like, False if regular comment')),
                ('reaction_type', models.CharField(blank=True, choices=[('like', '👍 Thích'), ('love', '❤️ Yêu thích'), ('insightful', '💡 Hữu ích'), ('learned', '📚 Học được nhiều')], help_text='Type of reaction if is_reaction=True', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cases.case')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threaded discussions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments_comment',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_reaction', True)), fields=('case', 'author'), name='unique_reaction_per_user_per_case')],
            },
        ),
    ]
