# Generated by Django 4.2.7 on 2025-11-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_add_reaction_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_comm_case_react_idx',
        ),
    ]
