# Generated by Django 5.2.9 on 2026-01-05 00:23

import django.db.models.deletion
import inquiries.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Subject of the inquiry', max_length=255)),
                ('content', models.TextField(help_text='Markdown supported content')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('topic', models.CharField(blank=True, help_text='Topic/Category (e.g., Diagnosis, Treatment, Documentation)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(help_text='The case this inquiry discusses', on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='cases.case')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_inquiries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'db_table': 'inquiries_inquiry',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Markdown supported content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_responses', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inquiries.inquiry')),
            ],
            options={
                'verbose_name': 'Inquiry Response',
                'verbose_name_plural': 'Inquiry Responses',
                'db_table': 'inquiries_inquiryresponse',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=inquiries.models.inquiry_file_upload_to)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(blank=True, help_text='Attach to the main inquiry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inquiries.inquiry')),
                ('response', models.ForeignKey(blank=True, help_text='Attach to a specific response', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inquiries.inquiryresponse')),
            ],
            options={
                'db_table': 'inquiries_inquiryattachment',
            },
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['case'], name='inquiries_i_case_id_a0152b_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status'], name='inquiries_i_status_8fae14_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['instructor'], name='inquiries_i_instruc_60ac92_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['student'], name='inquiries_i_student_a31e48_idx'),
        ),
    ]
