# Generated by Django 5.2.9 on 2026-01-05 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vietnamese_name', models.CharField(blank=True, help_text='Tên tiếng Việt', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Kho lưu trữ có hiển thị với tất cả người dùng')),
                ('access_level', models.CharField(choices=[('public', 'Công khai'), ('department', 'Khoa phòng'), ('private', 'Riêng tư')], default='private', help_text='Mức độ truy cập', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Khoa phòng sở hữu kho lưu trữ này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='cases.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kho lưu trữ',
                'verbose_name_plural': 'Kho lưu trữ',
                'db_table': 'repositories_repository',
                'ordering': ['-created_at'],
            },
        ),
    ]
