# Generated by Django 4.2.7 on 2025-10-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_department_alter_case_options_case_admission_date_and_more'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kho lưu trữ', 'verbose_name_plural': 'Kho lưu trữ'},
        ),
        migrations.AddField(
            model_name='repository',
            name='access_level',
            field=models.CharField(choices=[('public', 'Công khai'), ('department', 'Khoa phòng'), ('private', 'Riêng tư')], default='private', help_text='Mức độ truy cập', max_length=20),
        ),
        migrations.AddField(
            model_name='repository',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Khoa phòng sở hữu kho lưu trữ này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='cases.department'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Kho lưu trữ có hiển thị với tất cả người dùng'),
        ),
    ]
