# Generated by Django 4.2.7 on 2025-10-03 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('general', 'General Feedback'), ('clinical_reasoning', 'Clinical Reasoning'), ('documentation', 'Documentation Quality'), ('presentation', 'Presentation Skills')], default='general', max_length=30)),
                ('content', models.TextField()),
                ('strengths', models.TextField(blank=True, help_text='What the student did well')),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Areas where the student can improve')),
                ('recommendations', models.TextField(blank=True, help_text='Specific recommendations for improvement')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this feedback is visible to the student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='cases.case')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'db_table': 'feedback_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
